#!/bin/bash
set -e
[ -z $1 ] && echo "Usage: $0 /path/to/destination_image.png" && exit 1
id="$(xwininfo |grep "^xwininfo: Window id:"|cut -d \  -f 4)"
import -silent -window $id -gravity East -crop +14+30 $1
