#!/bin/bash
# https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality/556031#556031
# https://unix.stackexchange.com/questions/35282/convert-ogv-video-to-gif-animation

[ -z "$1" -o ! -f "$1" ] && echo "Usage: $0 <file>" && exit 1

tmp=$RANDOM_xp
FPS=10
WIDTH=640

ffmpeg -i "$1" -vf fps=$FPS,scale=$WIDTH:-1:flags=lanczos,palettegen $tmp.png
ffmpeg -i "$1" -i $tmp.png -loop 0 -filter_complex "fps=$FPS,scale=$WIDTH:-1:flags=lanczos[x];[x][1:v]paletteuse" "$1.gif"
convert "$1.gif" -coalesce -layers RemoveDups -fuzz 2% +dither -remap "$1.gif"[0] -layers OptimizePlus "$1.gif"
rm "$tmp.png"
